---
# vars file for 01_install_vsftpd
#
vsftpd_packages:
   - vsftpd
   - policycoreutils-python-utils

vsftpd_service: vsftpd

vsftpd_config_file: /etc/vsftpd/vsftpd.conf

vsftpd_upload_folder: /var/ftp/pub/upload
vsftpd_anon_root: /var/ftp/pub/

vsftpd_options:
   - key: xferlog_enable
     value: 'YES'
   - key: xferlog_file
     value: /var/log/vsftp_xfer.log
   - key: anon_root
     value: "{{ vsftpd_anon_root }}"

